id = "fleeting-theme"
name = "Fleeting Themes"
version = "0.0.2"
schema_version = 1
authors = ["fleetingecho <fleetingecho@duck.com>"]
description = "Fleeting Themes"
repository = "https://github.com/FleetingEcho/zed-fleeting-theme"
